### ISSUE TITLE
--invertblock but for individual blocks (not chunks)

### ISSUE THREAD

**Issue by thelampgod** [DaMatrix/SaveSearcher#6]
I want to be able to search for y0 that doesn't contain bedrock. so you would also need to combine it with --blockinrange somehow

**Comment by DaMatrix** [comment]
How about renaming the current `,invert` option to `,chunkinvert` and adding a new `,invert` option that has the behavior you're requesting?

**Comment by thelampgod** [comment]
sounds good!

**Comment by DaMatrix** [comment]
Compiled jar with fix is at https://github.com/DaMatrix/SaveSearcher/releases/tag/1.5.2

**Comment by thelampgod** [comment]
Wtf so quick! Thanks!!
