### ISSUE TITLE
Option for outputting the amount of blocks per chunk

### ISSUE THREAD

**Issue by Yqey** [DaMatrix/SaveSearcher#7]
So I want to figure out which chunk has the least amount of bedrock in the world, for that I need to analyze every chunk in a world and make it output a spreadsheet with the amounts of each block per chunk.

There should be an option to instead of listing the coordinates, that it instead lists the amount of block per chunk in to an output spreadsheet.

Using MCEdit's analyze function isn't an option as it would take days to manually analyze every single chunk.

**Comment by DaMatrix** [comment]
How about something like `--count,type=block,id=minecraft:bedrock`?

**Comment by Yqey** [comment]
Does that output the block amount per chunk?

**Comment by DaMatrix** [comment]
It would, yes.

(((it doesn't exist yet, that's a suggestion as to how it might work once i've added it)))

**Comment by Yqey** [comment]
Well that was fast, also how come literally every concievable useful 2b2t related program has been and was created by you?

**Comment by DaMatrix** [comment]
I'll take that answer as a "yes" and get straight to adding a `--count` mode.

As to your question: writing code for block game is more fun than block game. Also, I made this and RegionMerger so I could do the merging for the 100k map.

**Comment by DaMatrix** [comment]
Compiled jar is at https://github.com/DaMatrix/SaveSearcher/releases/tag/1.5.3
