### ISSUE TITLE
CSV output improperly formatted

### ISSUE THREAD

**Issue by Yqey** [DaMatrix/SaveSearcher#8]
When you do a count operation, instead of listing the coordinates of the chunk in one column and the amount of blocks in another one, it instead lists everything in the same column.¨

![image](https://user-images.githubusercontent.com/50055580/71595452-0b8c5600-2b3c-11ea-92bc-a96626b3c95b.png)

**Comment by DaMatrix** [comment]
the CSV output is formatted correctly, and it loads correctly in libreoffice.

**Comment by DaMatrix** [comment]
actually, could you send the CSV as an attachment here? looking at that screenshot there seems to be more wrong than just broken formatting (i see what seem to be missing values on some lines)

**Comment by Yqey** [comment]
https://cdn.discordapp.com/attachments/661276955609661450/661277025952071690/Count_-_Block_idminecraft_bedrock.csv This is the outputted file

**Comment by DaMatrix** [comment]
![image](https://user-images.githubusercontent.com/11216106/71620391-0d9cf600-2bca-11ea-98db-deb706aa087d.png)

nope, that loads correctly as well. definitely an issue with the software you're using.

**Comment by thelampgod** [comment]
Instead of opening the file directly in Excel you need to import it, then it will show up correctly. Idk why

**Comment by DaMatrix** [comment]
Maybe you need to be using chad libreoffice ;-)
