### ISSUE TITLE
Invert seems to give chunk relative coordinates (0-15)

### ISSUE THREAD

**Issue by thelampgod** [DaMatrix/SaveSearcher#9]
![bild](https://user-images.githubusercontent.com/24843414/71877487-8d2a4800-3129-11ea-862b-79ac6c6e77ee.png)

When using the invert option all the results are in the range 0-15 (which is wrong)

My command:
`java -jar SaveSearcher-1.5.4.jar --input="C:/Users/thela/Desktop/2b2t 100k/2b2t_100k_final" --dim=0 -v --output="100k/y0bedrock" --block,id=minecraft:bedrock,min=0,max=0,invert=true
`

**Comment by DaMatrix** [comment]
fixed, will make release once i get home (on mobile at school atm)
